version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install dbt-athena-community

  pre_build:
    commands:
      - mkdir -p ~/.dbt
      - echo "climabr:" > ~/.dbt/profiles.yml
      - echo "  target: prod" >> ~/.dbt/profiles.yml
      - echo "  outputs:" >> ~/.dbt/profiles.yml
      - echo "    prod:" >> ~/.dbt/profiles.yml
      - echo "      type: athena" >> ~/.dbt/profiles.yml
      - echo "      database: awsdatacatalog" >> ~/.dbt/profiles.yml
      - echo "      region_name: us-east-1" >> ~/.dbt/profiles.yml
      - echo "      schema: landing" >> ~/.dbt/profiles.yml
      - echo "      s3_staging_dir: s3://proj-clima-dbt-hp/dbt/metadados/" >> ~/.dbt/profiles.yml
      - echo "      s3_data_dir: s3://proj-clima-dbt-hp/dbt/table/" >> ~/.dbt/profiles.yml
      - echo "      threads: 4" >> ~/.dbt/profiles.yml
      - dbt debug

  build:
    commands:
      - dbt deps
      - dbt run
      - dbt test
      - dbt docs generate
      - BUILD_DATE=$(date +%d/%m/%Y_%H:%M)
      - sed -i "s|</body>|<p style=\"text-align:center;font-size:11px;color:#666;margin-top:40px;\">Updated: $BUILD_DATE</p></body>|" target/index.html

  post_build:
    commands:
      - aws s3 sync target/ s3://www.cimabrhp.com --delete --region us-east-1

artifacts:
  files:
    - target/**/*
